#if DIMENSIONAL_ANALYSIS
    global using Metrology;
    global using static Metrology.Meter;
    global using static Metrology.Second;
    global using static Metrology.Kilogram;
    global using static Metrology.Mole;
    global using static Metrology.Centimeter;
    global using static Metrology.Millimeter;
    global using static Metrology.Inch;
    global using static Metrology.Foot;
    global using static Metrology.Yard;
    global using static Metrology.Mile;
    global using static Metrology.Minute;
    global using static Metrology.Hour;
    global using static Metrology.Gram;
    global using static Metrology.Microgram;
    global using static Metrology.Radian;
    global using static Metrology.Degree;
    global using static Metrology.Hertz;
    global using static Metrology.Event_Hour;
    global using static Metrology.Meter2;
    global using static Metrology.Meter3;
    global using static Metrology.Meter_Sec;
    global using static Metrology.Centimeter_Sec;
    global using static Metrology.Meter_Sec2;
    global using static Metrology.Meter2_Sec2;
    global using static Metrology.Meter2_Sec;
    global using static Metrology.Gram_Meter;
    global using static Metrology.Gram_Mile;
    global using static Metrology.Microgram_Meter;
    global using static Metrology.Gram_Meter3;
    global using static Metrology.Microgram_Meter3;
    global using static Metrology.Meter3_Mole;
    global using static Metrology.Gram_Mole;
    global using static Metrology.Microgram_Mole;
    global using static Metrology.Microgram_MeterSec;
    global using static Metrology.Gram_MileHour;
    global using static Metrology.Ratio;
    global using static Metrology.PPM;
    global using static Metrology.Math;
#else
    global using Meter = System.Double;
    global using Second = System.Double;
    global using Kilogram = System.Double;
    global using Mole = System.Double;
    global using Centimeter = System.Double;
    global using Millimeter = System.Double;
    global using Inch = System.Double;
    global using Foot = System.Double;
    global using Yard = System.Double;
    global using Mile = System.Double;
    global using Minute = System.Double;
    global using Hour = System.Double;
    global using Gram = System.Double;
    global using Microgram = System.Double;
    global using Radian = System.Double;
    global using Degree = System.Double;
    global using Hertz = System.Double;
    global using Event_Hour = System.Double;
    global using Meter2 = System.Double;
    global using Meter3 = System.Double;
    global using Meter_Sec = System.Double;
    global using Centimeter_Sec = System.Double;
    global using Meter_Sec2 = System.Double;
    global using Meter2_Sec2 = System.Double;
    global using Meter2_Sec = System.Double;
    global using Gram_Meter = System.Double;
    global using Gram_Mile = System.Double;
    global using Microgram_Meter = System.Double;
    global using Gram_Meter3 = System.Double;
    global using Microgram_Meter3 = System.Double;
    global using Meter3_Mole = System.Double;
    global using Gram_Mole = System.Double;
    global using Microgram_Mole = System.Double;
    global using Microgram_MeterSec = System.Double;
    global using Gram_MileHour = System.Double;
    global using Ratio = System.Double;
    global using PPM = System.Double;
    global using static System.Math;
#endif
